// <auto-generated />
namespace CarFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Carrequiresowner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Carrequiresowner));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310704529_Car requires owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
